"""Re-initializing the models

Revision ID: 07a6dfb46533
Revises: 
Create Date: 2025-12-03 15:56:56.513379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a6dfb46533'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', postgresql.ENUM('seeker', 'owner', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('house_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('payment_duration', postgresql.ENUM('monthly', 'anually', name='payment_duration'), nullable=False),
    sa.Column('bedroom_count', sa.Integer(), nullable=False),
    sa.Column('security', postgresql.ENUM('highly_secured', 'secured_to_some_extent', 'not_secured', name='environment_security'), nullable=False),
    sa.Column('water', postgresql.ENUM('tap_inside', 'tap_outside', 'tap_nearby', 'well_outside', 'well_nearby', 'no_nearby_water_source', name='water_accessibility'), nullable=False),
    sa.Column('power', postgresql.ENUM('very_stable', 'stable', 'not_stable', name='power_stability'), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('parking_space', sa.Boolean(), nullable=False),
    sa.Column('ac', sa.Boolean(), nullable=False),
    sa.Column('kitchen', sa.Boolean(), nullable=False),
    sa.Column('gym', sa.Boolean(), nullable=False),
    sa.Column('tv', sa.Boolean(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_house_title'), 'houses', ['house_title'], unique=False)
    op.create_index(op.f('ix_houses_institution'), 'houses', ['institution'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_institution'), table_name='houses')
    op.drop_index(op.f('ix_houses_house_title'), table_name='houses')
    op.drop_table('houses')
    op.drop_table('users')
    # ### end Alembic commands ###
