"""Autogenerate to current state

Revision ID: e48f2ea610f2
Revises: 07a6dfb46533
Create Date: 2026-02-13 20:03:34.711240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e48f2ea610f2'
down_revision: Union[str, Sequence[str], None] = '07a6dfb46533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('local', 'google', name='auth_provider_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='user_provider_constraint')
    )
    op.add_column('houses', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.alter_column('houses', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(op.f('houses_user_id_fkey'), 'houses', type_='foreignkey')
    op.create_foreign_key('user_id', 'houses', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('houses', 'user_id')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('houses', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('user_id', 'houses', type_='foreignkey')
    op.create_foreign_key(op.f('houses_user_id_fkey'), 'houses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('houses', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('houses', 'owner_id')
    op.drop_table('auth_provider')
    # ### end Alembic commands ###
